-- Tariff/plan definitions. Master data for what each plan offers.
CREATE TABLE TARIFFS (
  TARIFF_ID      NUMBER(4)        PRIMARY KEY,
  NAME           VARCHAR2(100)    NOT NULL,
  MONTHLY_FEE    NUMBER(10,2)     NOT NULL CHECK (MONTHLY_FEE >= 0),
  DATA_LIMIT     NUMBER(10)       NOT NULL CHECK (DATA_LIMIT >= 0),
  MINUTE_LIMIT   NUMBER(10)       NOT NULL CHECK (MINUTE_LIMIT >= 0),
  SMS_LIMIT      NUMBER(10)       NOT NULL CHECK (SMS_LIMIT >= 0)
);

-- Customer master. TARIFF_ID FK enforces referential integrity to TARIFFS.
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID    NUMBER(8)        PRIMARY KEY,
  NAME           NVARCHAR2(100)   NOT NULL,
  CITY           NVARCHAR2(100)   NOT NULL,
  SIGNUP_DATE    DATE             NOT NULL,
  TARIFF_ID      NUMBER(4)        NOT NULL,
  CONSTRAINT FK_CUSTOMERS_TARIFF
    FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS (TARIFF_ID)
);

CREATE INDEX IX_CUSTOMERS_TARIFF_ID  ON CUSTOMERS (TARIFF_ID);
CREATE INDEX IX_CUSTOMERS_SIGNUP     ON CUSTOMERS (SIGNUP_DATE);
CREATE INDEX IX_CUSTOMERS_CITY       ON CUSTOMERS (CITY);
