-- Tariff/plan definitions. Master data for what each plan offers.
CREATE TABLE TARIFFS (
  TARIFF_ID      NUMBER(4)        PRIMARY KEY,
  NAME           VARCHAR2(100)    NOT NULL,
  MONTHLY_FEE    NUMBER(10,2)     NOT NULL CHECK (MONTHLY_FEE >= 0),
  DATA_LIMIT     NUMBER(10)       NOT NULL CHECK (DATA_LIMIT >= 0),
  MINUTE_LIMIT   NUMBER(10)       NOT NULL CHECK (MINUTE_LIMIT >= 0),
  SMS_LIMIT      NUMBER(10)       NOT NULL CHECK (SMS_LIMIT >= 0)
);

-- Customer master. TARIFF_ID FK enforces referential integrity to TARIFFS.
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID    NUMBER(8)        PRIMARY KEY,
  NAME           NVARCHAR2(100)   NOT NULL,
  CITY           NVARCHAR2(100)   NOT NULL,
  SIGNUP_DATE    DATE             NOT NULL,
  TARIFF_ID      NUMBER(4)        NOT NULL,
  CONSTRAINT FK_CUSTOMERS_TARIFF
    FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS (TARIFF_ID)
);

CREATE INDEX IX_CUSTOMERS_TARIFF_ID  ON CUSTOMERS (TARIFF_ID);
CREATE INDEX IX_CUSTOMERS_SIGNUP     ON CUSTOMERS (SIGNUP_DATE);
CREATE INDEX IX_CUSTOMERS_CITY       ON CUSTOMERS (CITY);

-- Current-month usage and payment per customer. Limits/fee are snapshotted
-- from TARIFFS at ingest (see ADR-0001). UNIQUE on CUSTOMER_ID enforces the
-- "one row per customer per month" rule.
CREATE TABLE MONTHLY_STATS (
  ID              NUMBER(10)      PRIMARY KEY,
  CUSTOMER_ID     NUMBER(8)       NOT NULL UNIQUE,
  DATA_LIMIT      NUMBER(10)      NOT NULL CHECK (DATA_LIMIT     >= 0),
  DATA_USAGE      NUMBER(12,2)    NOT NULL CHECK (DATA_USAGE     >= 0),
  MINUTES_LIMIT   NUMBER(10)      NOT NULL CHECK (MINUTES_LIMIT  >= 0),
  MINUTES_USAGE   NUMBER(10)      NOT NULL CHECK (MINUTES_USAGE  >= 0),
  SMS_LIMIT       NUMBER(10)      NOT NULL CHECK (SMS_LIMIT      >= 0),
  SMS_USAGE       NUMBER(10)      NOT NULL CHECK (SMS_USAGE      >= 0),
  MONTHLY_FEE     NUMBER(10,2)    NOT NULL CHECK (MONTHLY_FEE    >= 0),
  PAYMENT_STATUS  VARCHAR2(10)    NOT NULL
    CHECK (PAYMENT_STATUS IN ('PAID', 'UNPAID', 'LATE')),
  CONSTRAINT FK_MS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX IX_MS_PAYMENT_STATUS ON MONTHLY_STATS (PAYMENT_STATUS);
