LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/db/csv/CUSTOMERS.csv'
INTO TABLE CUSTOMERS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CUSTOMER_ID  INTEGER EXTERNAL,
  NAME         CHAR(100),
  CITY         CHAR(100),
  SIGNUP_DATE  DATE "DD/MM/YYYY",
  TARIFF_ID    INTEGER EXTERNAL
)
