OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/db/csv/MONTHLY_STATS.csv'
INTO TABLE MONTHLY_STATS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ID              INTEGER EXTERNAL,
  CUSTOMER_ID     INTEGER EXTERNAL,
  DATA_USAGE      DECIMAL EXTERNAL,
  MINUTES_USAGE   INTEGER EXTERNAL,
  SMS_USAGE       INTEGER EXTERNAL,
  PAYMENT_STATUS  CHAR(10),
  DATA_LIMIT      CONSTANT 0,
  MINUTES_LIMIT   CONSTANT 0,
  SMS_LIMIT       CONSTANT 0,
  MONTHLY_FEE     CONSTANT 0
)
