LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/db/csv/TARIFFS.csv'
INTO TABLE TARIFFS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  TARIFF_ID    INTEGER EXTERNAL,
  NAME         CHAR(100),
  MONTHLY_FEE  DECIMAL EXTERNAL,
  DATA_LIMIT   INTEGER EXTERNAL,
  MINUTE_LIMIT INTEGER EXTERNAL,
  SMS_LIMIT    INTEGER EXTERNAL
)
